language: python
python:
  - "3.6"

sudo: required
dist: trusty

branches:
  only:
    - master
    - dev

install:
  - pip install -r requirements.txt
script:
  - make html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GH_TOKEN}
  local_dir: build/html
  on:
    branch: master
